=== rsvato/camldoc-ru/bookinfo.dtd
<!ENTITY chap01 SYSTEM "./chapter01.xml">
<!ENTITY chap02 SYSTEM "./chapter02.xml">
<!ENTITY chap03 SYSTEM "./chapter03.xml">
<!ENTITY chap04 SYSTEM "./chapter04.xml">
<!ENTITY chap05 SYSTEM "./chapter05.xml">
<!ENTITY chap06 SYSTEM "./chapter06.xml">
<!ELEMENT bookinfo (title,subtitle?,authors,legal,part+)>
<!ELEMENT part (title,chap+)>
<!ELEMENT chap (ENTITIES)>
<!ATTLIST chap file CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT authors (main-author,sec-author?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT legal (#PCDATA)>
<!ATTLIST legal year CDATA #IMPLIED>
<!ELEMENT main-author (#PCDATA)>
<!ELEMENT sec-author (#PCDATA)>

=== rsvato/camldoc-ru/bookinfo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bookinfo SYSTEM "./bookinfo.dtd" [
        <!ENTITY chap01 SYSTEM "./chapter01.xml">
        <!ENTITY chap02 SYSTEM "./chapter02.xml">
        <!ENTITY chap03 SYSTEM "./chapter03.xml">
        <!ENTITY chap04 SYSTEM "./chapter04.xml">
        <!ENTITY chap05 SYSTEM "./chapter05.xml">
        <!ENTITY chap06 SYSTEM "./chapter06.xml">
        <!ENTITY chap07 SYSTEM "./chapter07.xml">
        <!ENTITY chap08 SYSTEM "./chapter08.xml">
        <!ENTITY chap09 SYSTEM "./chapter09.xml">
        <!ENTITY chap10 SYSTEM "./chapter10.xml">
        <!ENTITY chap11 SYSTEM "./chapter11.xml">
        <!ENTITY chap12 SYSTEM "./chapter12.xml">
        <!ENTITY char13 SYSTEM "./chapter13.xml">
        <!ENTITY char14 SYSTEM "./chapter14.xml">
]>
<bookinfo>
  <title>Система Objective Caml, релиз 3.10</title>
  <subtitle>Документация и руководство пользователя</subtitle>
  <authors>
    <main-author>Ксавье Леруа</main-author>
    <sec-author>Дамье Долигеc</sec-author>
    <sec-author>Жак Гарриг</sec-author>
    <sec-author>Дидье Реми</sec-author>
    <sec-author>Жером Вуйон</sec-author>
  </authors>
  <legal year="2008">
    Национальный Институт Исследований в области Информатики и Автоматики
  </legal>
  <part>
    <title>Введение в Objective Caml</title>
    <chap file="chapter01.html">&chap01;</chap>
    <chap file="chapter02.html">&chap02;</chap>
    <chap file="chapter03.html">&chap03;</chap>
    <chap file="chapter04.html">&chap04;</chap>
    <chap file="chapter05.html">&chap05;</chap>
  </part>
  <part>
    <title>Язык Оbjective Caml</title>
    <chap file="chapter06.html" nf="1">&chap06;</chap>
    <chap file="chapter07.html">&chap07;</chap>
  </part>
  <part>
    <title>Инструменты Objective Caml</title>
    <chap file="chapter08.html">&chap08;</chap>
    <chap file="chapter09.html">&chap09;</chap>
    <chap file="chapter10.html">&chap10;</chap>
    <chap file="chapter11.html">&chap11;</chap>
    <chap file="chapter12.html">&chap12;</chap>
    <chap file="chapter13.html">&char13;</chap>
    <chap file="chapter14.html">&char14;</chap>
  </part>
  <advice>
    <p>Исходники перевода находятся <a href="https://github.com/rsvato/camldoc-ru">тут</a>.</p>
  </advice>
</bookinfo>
